CREATE TABLE IF NOT EXISTS callback (
  callback_id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  number VARCHAR(20) NOT NULL,
  course VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  oncall BOOLEAN DEFAULT FALSE
);
